# Generated by Django 4.1.3 on 2022-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todonote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
