# Generated by Django 4.1.3 on 2022-11-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todonote_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
