# Generated by Django 4.1.3 on 2022-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todonote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='category',
            field=models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly'), ('q', 'Quarterly'), ('y', 'Yearly')], default='d', max_length=20),
        ),
    ]
